ref(osm/*): rename osm mesh delete to osm mesh uninstall
openservicemesh/osm pull request #1665
Opened 2020-09-04 02:35 UTC by shalier

Rename to more accurately describe command
and resolves #1622

Please mark with X for applicable areas.

- New Functionality      [ ]
- Documentation          [X ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [X ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests / CI System      [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

2020-09-04 15:47 UTC, draychev reviewed
@shalier Thank you for the change!

You can run `go fmt ./...` to auto-format all files in the repo and push another commit - this will fix the lint issue and pass CI.

Also I'd reccomend using `git mv cmd/cli/mesh_delete.go cmd/cli/mesh_uninstall.go`, which will preserve the history of the file (right now it looks like delete + add)

2020-09-04 16:06 UTC, shashankram commented
> Also I'd reccomend using `git mv cmd/cli/mesh_delete.go cmd/cli/mesh_uninstall.go`, which will preserve the history of the file (right now it looks like delete + add)

Please use `git mv` if it isn't the case to preserve history.

2020-09-04 19:21 UTC, ksubrmnn requested changes

2020-09-04 19:21 UTC, ksubrmnn commented on cmd/cli/mesh_uninstall.go
> +given the mesh name and namespace. It will not uninstall the namespace
This should still say "delete the namespace"

2020-09-04 19:30 UTC, ksubrmnn approved these changes

2020-09-04 20:08 UTC, shashankram approved these changes

2020-09-04 22:37 UTC, merged

2020-09-08 18:00 UTC, michelleN commented
@shalier - thanks for the change. Please remember to hit "Squash and Merge" when you have an approved pull request or are merging community pull requests.