Fix when enableSidecarInjection=false, the annotation is not removed.
openservicemesh/osm pull request #1728
Opened 2020-09-18 08:24 UTC by wenxinnnnn

Please describe the motivation for this PR and provide enough information so that others can review it.
Refer to #1727 

Please mark with X for applicable areas.

- CLI Tool               [X]

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

2020-09-18 11:03 UTC, wenxinnnnn commented
run test found a kubernetes bug。refer to https://github.com/kubernetes/kubernetes/issues/94887

2020-09-18 16:20 UTC, shashankram commented
Let's discuss the expected behavior on #1727 before proceeding with this change.

2020-09-18 23:49 UTC, ksubrmnn commented on cmd/cli/namespace_add.go
> +		},
Please modify this so that the annotation is only removed if `cmd.Flags().Changed("enable-sidecar-injection") && a.enableSidecarInjection == false`

2020-09-18 23:51 UTC, ksubrmnn requested changes

2020-09-18 23:51 UTC, ksubrmnn commented on cmd/cli/namespace_add.go
> +		},
Please modify this so that the annotation is only removed if `cmd.Flags().Changed("enable-sidecar-injection") && a.enableSidecarInjection == false`

2020-09-19 15:39 UTC, wenxinnnnn commented
osm namespace add bookstore # Do not enable sidecar injection/ Do not change sidecar annotation label
osm namespace add bookstore --enable-sidecar-injection # Enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection=true # Enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection=false # Do not enable sidecar injection / Remove label

2020-09-21 22:11 UTC, ksubrmnn commented on cmd/cli/namespace_test.go
> +		Context("Given one namespace as an arg with sidecar injection disable", func() {
Change to:

"Given one namespace as an arg with sidecar injection explicitly set to false"

2020-09-21 22:13 UTC, ksubrmnn requested changes
Looks great! Just need to fix up the test a bit

2020-09-21 22:13 UTC, ksubrmnn commented on cmd/cli/namespace_test.go
> +			It("should correctly add a label to the namespace", func() {
Change to "should correctly add a monitor label to the namespace"

2020-09-21 22:13 UTC, ksubrmnn commented on cmd/cli/namespace_test.go
> +				ns, err := fakeClientSet.CoreV1().Namespaces().Get(context.TODO(), testNamespace, metav1.GetOptions{})
Change to "should not add an inject label to the namespace"

2020-09-22 19:29 UTC, ksubrmnn approved these changes

2020-09-23 02:56 UTC, wenxinnnnn commented on cmd/cli/namespace_add.go
> +	f.BoolVar(&namespaceAdd.enableSidecarInjection, "enable-sidecar-injection", true, "Enable automatic sidecar injection")
Now this true only indicates the default value when enable sidecar injection is explicitly set.
sidecarInjectionFlagSet and enableSidecarInjection are both true, then the sidecar will be automatically injected.
The current changes do not change the previous cli usage habits.

2020-09-23 16:11 UTC, shashankram approved these changes

2020-09-23 16:13 UTC, merged