Updated e2e readme
openservicemesh/osm pull request #2450
Opened 2021-02-03 22:43 UTC by nshankar13

Signed-off-by: nshankar13 <nshankar@microsoft.com>

**Description**:
Provided additional information in the e2e readme as to how users can use the gingo.focus and test.timeout flags. 

**Affected area**:

- New Functionality      [ ]
- Documentation          [X]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [X]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

2021-02-03 22:47 UTC, nojnhuh approved these changes

2021-02-03 22:56 UTC, shashankram requested changes
Please squash your commits and also add commit descriptions to the commits in the PR and not just the PR description. This is pretty important because we have switched to using the merge option instead of squash.

2021-02-03 23:33 UTC, michelleN commented on tests/e2e/README.md
> +The `gingo.focus` flag can be used to run individual tests. The flag should specify the "Context" of the test they wish to run, which can be found in the `.go` file for that test. For instance, if yo
Is this supposed to be `ginkgo.focus`?

2021-02-04 03:49 UTC, eduser25 commented on tests/e2e/README.md
> +The `gingo.focus` flag can be used to run individual tests. The flag should specify the "Context" of the test they wish to run, which can be found in the `.go` file for that test. For instance, if yo
```suggestion
The `ginkgo.focus` flag can be used to run individual tests. The flag should specify the "Context" of the test they wish to run, which can be found in the `.go` file for that test. For instance, if you want to run the `e2e_tcp_client_server_test` with SMI policies, you should run: 
```

2021-02-04 17:11 UTC, michelleN approved these changes

2021-02-04 17:12 UTC, merged