xdslogs, fix race when multiple verticals write in xdslog map
openservicemesh/osm pull request #2456
Opened 2021-02-04 04:03 UTC by eduser25

There is a race when multiple envoys are connecting at the same time, where
multiple writes can happen on the xds log map.
Though rare, it's easy to hit with a beefier setup with more pods, or specially
when OSM restarts (since all pods will attempt to connect mostly at the same time).

-For now this is gated with a simple mutex. If this introduces unwanted penalties
we might rethink to just drop this in-memory logging and have regular logging do
the job.
- Also limitted the number of logs we can store at a time per proxy (before,
no upper limit)

Fixes #2441

Signed-off-by: Eduard Serra <eduser25@gmail.com>

**Affected area**:

- Control Plane          [x]

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

2021-02-04 17:10 UTC, shashankram commented on pkg/envoy/ads/debugger.go
> +	var logsCopy map[certificate.CommonName]map[envoy.TypeURI][]time.Time
👀

2021-02-04 17:10 UTC, shashankram commented on pkg/envoy/ads/debugger.go
> +	})
Could you drop a comment here on why this needs to be protected.

2021-02-04 17:10 UTC, shashankram commented on pkg/envoy/ads/profile.go
> +func (s *Server) trackXdsLog(cn certificate.CommonName, typeURL envoy.TypeURI) {
```suggestion
func (s *Server) trackXDSLog(cn certificate.CommonName, typeURL envoy.TypeURI) {
```

2021-02-04 17:45 UTC, snehachhabria approved these changes

2021-02-04 17:56 UTC, draychev requested changes
Could we use Go channels instead?

2021-02-04 18:42 UTC, eduser25 commented
@draychev could you be a bit more descriptive? I'd take channels anytime for inter-routine comms, but not to prevent multiple routines access the same resource. what's your idea?

2021-02-05 00:06 UTC, draychev approved these changes
@eduser25 thanks for the fix - I understand this is needed asap.

2021-02-05 00:15 UTC, eduser25 commented
Talked with Del, we might revisit this as we would like to avoid mutexes (though some sort of serialization cannot be avoided with current state of affairs) in favour of something else (channels?)

Double checking perf impact of the mutex and will merge after.

2021-02-05 00:52 UTC, merged