fix(cli): Add missing flags for upgrade
openservicemesh/osm pull request #2725
Opened 2021-03-03 20:43 UTC by nojnhuh

**Description**:
This change updates the `osm mesh upgrade` command with two additional
flags mapping to fields recently added to the osm-config ConfigMap:

`--outbound-ip-range-exclusion-list`

`--enable-privileged-init-container`

Fixes #2651

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [X]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

2021-03-03 21:06 UTC, snehachhabria approved these changes

2021-03-03 21:18 UTC, michelleN requested changes
Would be nice to add a small test for this change if possible.

2021-03-03 21:47 UTC, shashankram approved these changes

2021-03-03 21:47 UTC, shashankram commented on cmd/cli/mesh_upgrade.go
> +	f.StringSliceVar(&upg.outboundIPRangeExclusionList, "outbound-ip-range-exclusion-list", nil, "A global list of IP ranges to exclude from outbound traffic interception by the sidecar proxy. Pass once
```suggestion
	f.StringSliceVar(&upg.outboundIPRangeExclusionList, "outbound-ip-range-exclusion-list", nil, "A global list of IP ranges to exclude from outbound traffic interception by the sidecar proxy. Pass once per IP range or a single comma separated list of IP ranges of the form a.b.c.d/x")
```

2021-03-04 18:44 UTC, michelleN approved these changes

2021-03-04 18:44 UTC, merged