[wip] Add ValidateADSConfig for full ADS configurations
openservicemesh/osm pull request #2810
Opened 2021-03-11 05:38 UTC by eduser25

(this became a bit big because of the required API change, thanks for the patience)

Go-control-plane has some consistency check mechanisms for full
configurations, these however requires to construct a full snapshot
of a configuration (as a cache would expect) and then `Consistent()`
API can be called on it.

Please, refer to how `Consistent()` works below.
https://github.com/envoyproxy/go-control-plane/blob/v0.9.8/pkg/cache/v3/snapshot.go#L84

In order to be able to create a snapshot, the configurations have to
be available before marshalling. To avoid paying the cost to unmarshal all configurations
at `sendAll()` to check for config consistency, this commit has changed the XDS response
`handle()` to return `types.Resource`, which is a common interface in
go-control-plane to refer to typed resources to be sent through xDS regardless of their
TypeURI origin.

The most notable API change is the `sendAllResponse`, which has been renamed to `sendResponse`
and can now take any or multiple of the available TypeURIs that need to be sent, and will
run additional ADS validation if it is seen as a full ADS update.

Signed-off-by: edu <eduser25@gmail.com>

**Description**:

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

2021-03-12 22:58 UTC, draychev requested changes
@eduser25 it would be great to chunk this up into multiple PRs.
I suspect it would be possible to do it by xDS vertical, also function renames and refactors could go first.

2021-03-12 22:58 UTC, draychev commented on pkg/envoy/ads/response.go
> +func (s *Server) getXDSResource(tURI envoy.TypeURI, proxy *envoy.Proxy,
Would you be so kind to expand abbreviated variable names? I personally find it tough to read `tURI`. Subjectively I believe `typeURI` makes the code easier to read, lower cognitive load.

2021-03-12 22:58 UTC, draychev commented on pkg/envoy/ads/response.go
> +// getXDSResource function will invoke the right TypeURI handler for the resources associated with a proxy
It would be great to make the rename/refactor in a separate - much smaller PR - so it is easier and faster to review.

2021-03-12 22:58 UTC, draychev commented on pkg/envoy/ads/response.go
> +	// Order is important: CDS, EDS, LDS, RDS, SDS
I'd exclude SDS from this list.
Also, the link to @kyessenov's `go-control-plane` comment below on xDS ordering is from 2018 - we should check to see whether 3 years later this is still the case.

2021-03-13 18:41 UTC, eduser25 commented
As requested, I'll cut down this commit into smaller parts.

2021-03-13 18:41 UTC, closed without merging