feat(cmd/cli): add --delete-namespace flag to osm mesh uninstall
openservicemesh/osm pull request #3029
Opened 2021-03-29 17:24 UTC by niranjanative

Signed-off-by: Niranjan Gavade <niranjanative@gmail.com>
**Description**:

Add --delete-namespace flag to osm mesh uninstall to provide functionality of directly deleting the namespace after osm is uninstalled Fixes #3000 

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [X]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? No

2021-03-29 18:05 UTC, michelleN requested changes
Thank you @niranjanative ! Would you mind adding a test for this change?

2021-03-30 15:46 UTC, michelleN approved these changes
Thank you @niranjanative !

2021-04-09 23:10 UTC, draychev approved these changes
Thank you @niranjanative 
This seems like a useful improvement!

2021-04-14 04:48 UTC, draychev commented
@niranjanative Would you be so kind to rebase your branch with the latest from main. Looking at the changes - there were a few renames. Overall it should be possible to fix the merge conflicts and merge this PR.

2021-04-15 06:43 UTC, niranjan-gavade commented
> @niranjanative Would you be so kind to rebase your branch with the latest from main. Looking at the changes - there were a few renames. Overall it should be possible to fix the merge conflicts and merge this PR.

Thanks for resolving conflicts of this PR @draychev

2021-04-15 15:30 UTC, niranjanative commented
> @niranjanative Would you be so kind to rebase your branch with the latest from main. Looking at the changes - there were a few renames. Overall it should be possible to fix the merge conflicts and merge this PR.

Thanks @draychev for resolving conflicts on this PR

2021-04-15 23:14 UTC, draychev commented
@niranjanative I merged #3165 which contains your commits.  I wanted to get `main` to a state where this PR here would be mergeable - but it sounds like this won't be the case until you squash all the commits in this PR here.

Would you be able to
 1) `git rebase -i HEAD~5` and squash all 5 commits into one on your local branch and then 
 2) `git pull --rebase upstream main` on your local branch - because I applied #3165 you should not have to go through the headache of resolving merge conflicts
 3) `git push` your main - and this PR will be updated
 
 I believe then we will be able to close the PR and give credit where credit is due - YOU!
 
 Thank you SO much for contributing to OSM!

2021-04-16 05:40 UTC, niranjanative commented
> @niranjanative I merged #3165 which contains your commits. I wanted to get `main` to a state where this PR here would be mergeable - but it sounds like this won't be the case until you squash all the commits in this PR here.
> 
> Would you be able to
> 
> 1. `git rebase -i HEAD~5` and squash all 5 commits into one on your local branch and then
> 2. `git pull --rebase upstream main` on your local branch - because I applied #3165 you should not have to go through the headache of resolving merge conflicts
> 3. `git push` your main - and this PR will be updated
> 
> I believe then we will be able to close the PR and give credit where credit is due - YOU!
> 
> Thank you SO much for contributing to OSM!

Sure @draychev will do that. Thanks for guiding me here. Also, Thank you to you & all maintainers for creating this great project!

2021-04-16 07:37 UTC, closed without merging

2021-04-16 07:43 UTC, niranjanative commented
Hey @draychev tried following the steps you mentioned, looks like something went wrong

2021-04-16 16:13 UTC, shashankram commented
> Hey @draychev tried following the steps you mentioned, looks like something went wrong

@niranjanative Could you respin this PR as a single commit?

2021-04-16 16:47 UTC, draychev commented
@niranjanative I think everything looks great - I see you forced pushed here and now because I already merged your commits to `main` - this PR here says there is nothing more to do.
So your work, @niranjanative, is already in the repo and will be released with v0.9!
Thank you, sincerely!
Feel free to tackle anything else you might find interesting and reach out for help if you need it!

2021-04-16 16:55 UTC, shashankram commented
> @niranjanative I think everything looks great - I see you forced pushed here and now because I already merged your commits to `main` - this PR here says there is nothing more to do.
> So your work, @niranjanative, is already in the repo and will be released with v0.9!
> Thank you, sincerely!
> Feel free to tackle anything else you might find interesting and reach out for help if you need it!

Thanks @draychev for respinning and merging! (ref: https://github.com/openservicemesh/osm/pull/3165)

2021-04-16 17:34 UTC, niranjanative commented
Okay, that's great @draychev Thanks for the support @draychev @shashankram Currently going through the docs & will continue to contribute on simpler issues till then. Feel free to assign me any issue if you feel so. Also where should I reach out to you guys if I need help on something specific?