feat(multicluster/remote-outline): outline remote service
openservicemesh/osm pull request #3507
Opened 2021-06-04 02:26 UTC by timmyreilly

chart and api outline for remoteservice

Signed-off-by: timmyreilly <tireilly@microsoft.com>

**Description**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [X] |
| Documentation              | [ ] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | [ ] |
| CI System                  | [ ] |
| Demo                       | [ ] |
| Performance                | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?
No
1. Is this a breaking change?
No

2021-06-04 16:07 UTC, shashankram reviewed
Hey @timmyreilly, thanks for contributing.

To simplify reviews, would you mind breaking this change up as follows:
1. CRD definition
2. Go types and autogenerated code in pkg/apis
3. Helm chart changes (values.yaml and schema)
4. Go code changes in pkg/config
5. Integrate with osm-controller using a feature flag

2021-06-04 17:04 UTC, timmyreilly commented
@shashankram can do!

2021-06-04 17:15 UTC, snehachhabria requested changes

2021-06-04 17:15 UTC, snehachhabria commented on charts/osm/values.yaml
> +  enableMulticluster: false
I have already created a feature flag for this here : https://github.com/openservicemesh/osm/blob/4c390a5026874c5e35f52457dc9fb1c818375ea0/charts/osm/values.yaml#L227

Please could we use this

2021-06-04 17:15 UTC, snehachhabria commented on charts/osm/crds/remoteservice.yaml
> +  group: multicluster.openservicemesh.io
As discussed offline we want this to be a part of the `config.openservicemesh.io` that already exists

2021-06-04 17:15 UTC, snehachhabria commented on charts/osm/crds/remoteservice.yaml
> +  name: remoteservices.multicluster.openservicemesh.io
```suggestion
  name: remoteservices.config.openservicemesh.io
```

2021-06-07 21:58 UTC, timmyreilly commented on pkg/announcements/types.go
> +	ConfigDeleted AnnouncementType = "config-deleted"
To be MultiClusterServiceAdded

2021-06-07 21:58 UTC, timmyreilly commented on pkg/apis/config/v1alpha1/register.go
> +		&RemoteService{},
MulticlusterService + MulticluasterServiceList

2021-06-07 22:00 UTC, timmyreilly commented on pkg/kubernetes/types.go
> +	RemoteServices InformerKey = "RemoteServices"
MulticlusterServices InformerKey = "MulticlusterServices

2021-06-10 00:19 UTC, closed without merging