Demo port
openservicemesh/osm pull request #3619
Opened 2021-06-17 21:22 UTC by allenlsy

**Description**:

Support configuring the port number for bookstore and bookwarehouse services in the demo. They can be configured using the `BOOKSTORE_PORT` and `BOOKWAREHOUSE_PORT` in `.env`.

Manual tested by customizing port number to `12001` in `.env` . The demo works as expected.

![Screen Shot 2021-06-17 at 2 09 15 PM](https://user-images.githubusercontent.com/872876/122473888-4fb12780-cf77-11eb-8391-87b29466199a.png)

![Screen Shot 2021-06-17 at 2 08 33 PM](https://user-images.githubusercontent.com/872876/122473901-5475db80-cf77-11eb-8b27-19604d63d0e1.png)

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| Documentation              | [ ] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | [ ] |
| CI System                  | [ ] |
| Demo                       | [X] |
| Performance                | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

No

1. Is this a breaking change?

No

2021-06-17 21:33 UTC, shashankram requested changes
I saw the issue https://github.com/openservicemesh/osm/issues/2755 and we settled on port 14001 (a pretty unique port that's not going to be commonly used elsewhere). I don't see why we are trying to introduce more complexity in the automated demo with trying to make the port configurable.

I am inclined to close https://github.com/openservicemesh/osm/issues/2755 unless there is a reason it is absolutely needed.

2021-06-17 21:36 UTC, allenlsy commented
@ksubrmnn is this the reason we want make it configurable?

https://github.com/openservicemesh/osm/pull/2583#issuecomment-791749920

2021-06-17 23:20 UTC, allenlsy commented
Closing the PR, since we haven't mutually agreed working on it.

2021-06-29 17:46 UTC, snehachhabria approved these changes

2021-06-29 17:46 UTC, snehachhabria commented on .env.example
> +
should the bookthief port all be configured ?

2021-06-29 20:50 UTC, allenlsy commented
Closing the PR as the feature is not required, and we want to keep our demo app simple.

2021-06-29 20:50 UTC, closed without merging