Create noinstall nightly job
openservicemesh/osm pull request #3690
Opened 2021-06-29 18:33 UTC by nshankar13

**Description**: Add a no-install nightly job that creates a kind cluster, installs OSM via OSM CLI, and runs the e2e suite with the "NoInstall" flag enabled. These will run off of main. The pipeline will be part of the project iOpenServiceMesh project within the ADO Upstream Org. 

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| Documentation              | [ ] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | [X] |
| CI System                  | [X] |
| Demo                       | [ ] |
| Performance                | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?
No
1. Is this a breaking change?
No

2021-06-29 18:41 UTC, shashankram requested changes
Why is there a binary file for Kind in this change?

2021-06-29 18:45 UTC, shashankram requested changes
Why can't this be a nightly github action similar to our existing PR and Push actions? This is easily possible using https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events.

2021-07-02 19:08 UTC, snehachhabria approved these changes

2021-07-02 19:21 UTC, shashankram approved these changes
Thanks @nshankar13

2021-07-06 15:42 UTC, merged