fix(e2e): disable flakey fluent bit output e2e
openservicemesh/osm pull request #4124
Opened 2021-09-16 20:04 UTC by SanyaKochhar

**Description**: Resolves #3138 by disabling the test

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution?
   

2. Is this a breaking change?
no

2021-09-16 20:08 UTC, nojnhuh requested changes
Can we instead disable this by setting its `Bucket` to 0 (or anything other than 1-10) here? https://github.com/openservicemesh/osm/blob/dab76017b2c4714e72fe973c40c77c2c7d720017/tests/e2e/e2e_fluentbit_output_test.go#L22

Just to save us from making the `go test` calls in the CI config more unwieldy than they already are.

2021-09-17 16:24 UTC, SanyaKochhar commented
> Can we instead disable this by setting its `Bucket` to 0 (or anything other than 1-10) here?

Yeah makes sense, updated to do this instead

2021-09-17 16:28 UTC, nojnhuh approved these changes

2021-09-17 16:32 UTC, shashankram approved these changes

2021-09-21 13:54 UTC, merged