docs(demo): update manual demo manifests
openservicemesh/osm pull request #4180
Opened 2021-09-28 15:44 UTC by nojnhuh

**Description**:
These changes coincide with the changes made to the manual demo here:
https://github.com/openservicemesh/osm-docs/pull/195

The changes include:

- Adding bookwarehouse SMI policies
- Renaming bookstore backend service to bookstore-v1
- Updating links to docs

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [X] |
| Documentation              | [X] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? No
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change? No

2021-10-30 21:57 UTC, trstringer requested changes

2021-10-30 21:57 UTC, trstringer commented on docs/example/manifests/access/traffic-access-v1-allow-bookthief.yaml
> +  name: tcp-route
Could you rename this from `tcp-route` to something more indicative of its use? Maybe `mysql`? Or possibly `mysql-tcp`?

2021-10-30 21:57 UTC, trstringer commented on docs/example/manifests/access/traffic-access-v1.yaml
> +  name: tcp-route
Same as above, use a name that explains its usage instead of resource type.

2021-11-01 16:19 UTC, shashankram approved these changes

2021-11-01 16:33 UTC, trstringer approved these changes

2021-11-01 16:56 UTC, snehachhabria approved these changes

2021-11-01 17:05 UTC, merged