chore(release): update version to v0.11.0-rc.1
openservicemesh/osm pull request #4200
Opened 2021-09-30 21:32 UTC by jaellio

Signed-off-by: jaellio <jaellio@microsoft.com>

- [ ] I have cherry-picked any changes [labelled](https://github.com/openservicemesh/osm/labels) `needs-cherry-pick-vX.Y.Z`
- [ ] I have made all of the following version and patch updates:
  1. Updated the container image tag in charts/osm/values.yaml
  2. Updated the chart **and** app version in charts/osm/Chart.yaml
  3. Updated the image tags used in the demo manifests
  4. Regenerated the Helm chart README.md

- [ ] I have checked that the base branch for this PR is correct as defined by the release guide

Is this a release candidate?

2021-09-30 21:50 UTC, snehachhabria approved these changes

2021-10-01 00:03 UTC, nojnhuh approved these changes

2021-10-01 17:49 UTC, shashankram commented
@jaellio could you rebase this PR to the HEAD of release-v0.11.

2021-10-01 17:54 UTC, shashankram requested changes
@jaellio I forgot when I suggested altering the logic in the Helm template that we only want to be setting the image tags in `values.yaml` for the PR workflow. The behavior should be that image digests get used by default for which image tags must not be encoded in `values.yaml`. So we can pass in the image tag from the CI instead of setting the default.

2021-10-01 17:54 UTC, shashankram commented on charts/osm/values.yaml
> +    tag: "v0.11.0-rc.1"
We want to be setting this tag only from the CI job for the PR workflow, otherwise, the default images will also use tags instead of digests.

2021-10-01 17:59 UTC, shashankram approved these changes

2021-10-01 17:59 UTC, shashankram commented on charts/osm/values.yaml
> +    tag: ""
Would be helpful to add a comment here that the tag must not be set on release branches.

2021-10-01 17:59 UTC, shashankram commented on .github/workflows/openshift-nightly.yml
> +on:
nit: unrelated to this PR.

2021-10-01 18:16 UTC, shashankram approved these changes

2021-10-01 18:18 UTC, snehachhabria approved these changes

2021-10-01 18:19 UTC, eduser25 approved these changes

2021-10-01 18:38 UTC, merged