Updated installation link
openservicemesh/osm pull request #4389
Opened 2021-12-06 15:59 UTC by mudit-01

Updated link as per discussion in PR https://github.com/openservicemesh/osm/pull/4358 

Signed-off-by: mudit singh <mudit.singh@india.nec.com>

**Description**:

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [X ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

2021-12-06 16:10 UTC, mudit-01 commented
opened with some changes to  @prapakaransp PR

2021-12-06 16:17 UTC, shashankram approved these changes

2021-12-06 16:19 UTC, nojnhuh requested changes
Like I mentioned in https://github.com/openservicemesh/osm/pull/4344#issuecomment-964314421, this is already in sync with the main branch of the docs repo. Overall, I'd be in favor of closing this since we'd just need to change it back once v1.0 of the docs site is published.

2021-12-09 09:50 UTC, closed without merging

2021-12-09 09:50 UTC, mudit-01 commented
closing as requested by @nojnhuh