Improve distributed tracing
openservicemesh/osm pull request #4456
Opened 2022-01-14 23:09 UTC by allenlsy

**Description**:

There are some distributed tracing issues with the current demo application.

1. We want to see the tracing graph that connects bookbuyer -> bookstore -> bookwarehouse all together, while currently the chain is broken down into spans.
2. Some users mentioned that the trace ID should be 16 bytes, according to the OpenTracing specification [here](https://www.w3.org/TR/trace-context/#trace-id), while in OSM, the trace ID is 8 bytes, and the first span has the same span ID and trace ID. This can be a potential issue for some customers.

This PR fixes these issues by:

1. Enabling Envoy to generate 16 bytes trace ID.
2. Adds extra Zipkin tracing headers to the request in the demo application, so that Envoy can correctly generate tracing information for Jaeger to collect.

**Testing done**:

Deployed the demo application with `demo/run-demo-osm.sh`, and checked tracing graph on Jaeger again.

![Screen Shot 2022-01-14 at 2 51 50 PM](https://user-images.githubusercontent.com/872876/149596569-20f23b4d-9b30-463b-af29-6eee9aeb2ee3.png)

Note how the requests are linked together with the same trace ID `337a603dfe4a22ee` in the logs from bookbuyer, bookstore and bookwarehouse.

![Screen Shot 2022-01-14 at 2 52 56 PM](https://user-images.githubusercontent.com/872876/149596635-5d0b97cf-9a3c-413c-a3be-3cd532953449.png)

![Screen Shot 2022-01-14 at 2 53 43 PM](https://user-images.githubusercontent.com/872876/149596639-0110b1eb-2003-4975-a003-6b3b4df6da0b.png)

![Screen Shot 2022-01-14 at 2 53 59 PM](https://user-images.githubusercontent.com/872876/149596646-027ee077-6f93-4680-acd0-0dd8422781f5.png)

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [X] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [X] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

No

2. Is this a breaking change?

No

2022-01-18 13:03 UTC, trstringer requested changes

2022-01-18 13:03 UTC, trstringer commented on demo/cmd/bookwarehouse/bookwarehouse.go
> +	if r != nil {
You can remove a nested layer:

```suggestion
	if r == nil {
	    return
	}
```

2022-01-18 17:06 UTC, shashankram reviewed
Where is the header being set to 16 bytes instead of 8 as indicated in the commit?

2022-01-18 20:48 UTC, allenlsy commented
@shashankram I should update the PR description. That's not addressed in this PR.

2022-01-20 17:07 UTC, shashankram approved these changes
Thanks @allenlsy. Could you also document the required tracing headers in https://main--osm-docs.netlify.app/docs/guides/observability/tracing/

2022-01-20 17:57 UTC, jaellio approved these changes

2022-01-20 18:01 UTC, trstringer approved these changes

2022-01-20 18:46 UTC, snehachhabria approved these changes

2022-01-20 18:59 UTC, merged