apis: add MeshRootCertificate API types
openservicemesh/osm pull request #4677
Opened 2022-04-20 21:43 UTC by jaellio

**Description**:

Adds the Go types for the MeshRootCertificate API

Part of #4502

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [x] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change? no

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

2022-04-21 15:56 UTC, steeling approved these changes

2022-04-22 16:57 UTC, shashankram requested changes
The v1alpha1 version of the config API is being updated here, which is no longer used.

2022-04-22 16:57 UTC, shashankram commented on pkg/apis/config/v1alpha1/meshrootcertificate.go
> +	Provider *ProviderSpec `json:"provider,omitempty"`
Is there a reason the only field in the spec is optional? Does an empty spec mean something?

2022-04-22 18:13 UTC, shashankram approved these changes

2022-04-22 19:07 UTC, nojnhuh approved these changes

2022-04-22 19:08 UTC, merged