fix(): reduce minimum tls version for osm controller, verifier, health
openservicemesh/osm pull request #5292
Opened 2023-03-13 13:20 UTC by whitneygriffith

**Description**:
Backport the following fix for #5282 into release-v1.2

**Testing done**:
Confirmed demo, health check and verifier worked as expected when OSM control plane has the following configuration:

```
Tls Max Protocol Version:  TLSv1_2 
Tls Min Protocol Version:  TLSv1_2
```

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [x] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

2023-03-13 13:55 UTC, keithmattix requested changes
Changes look good, but could you add an E2E test to make sure we continuously verify that setting the sidecar to maxTLSVersion v1.2 does not break anything?

2023-03-17 19:40 UTC, whitneygriffith commented
> Changes look good, but could you add an E2E test to make sure we continuously verify that setting the sidecar to maxTLSVersion v1.2 does not break anything?

Added an e2e test

2023-03-20 15:06 UTC, keithmattix approved these changes
Good work; thanks for the tests! I assume there will be a follow-up PR removing unsupported versions (or just marking them as unsupported?

2023-03-20 18:11 UTC, whitneygriffith commented
> Good work; thanks for the tests! I assume there will be a follow-up PR removing unsupported versions (or just marking them as unsupported?

Yes! I will be creating a PR that will be removing TLSv1_0 and TLSv1_1 for the envoy max TLS Version.

2023-03-20 20:45 UTC, jaellio approved these changes

2023-03-20 21:30 UTC, merged